name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-ui
      IMAGE_TAG: v4
      IMAGE_NAME1: microtodo-ui
      IMAGE_TAG1: v1
      ACR_NAME: devtodoacrwestus
      ACR_LOGIN_SERVER: devtodoacrwestus.azurecr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 6c2702c6-118e-4640-aba9-86e61333ba0d
          tenant-id: 1658eae6-9066-4c87-8f0e-22a840432c57
          subscription-id: 20cadb7c-62d8-4c57-9b49-63ebd307c63e

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          
      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          
          ##########################

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME1:$IMAGE_TAG1 ./Micro

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME1:$IMAGE_TAG1 $ACR_LOGIN_SERVER/$IMAGE_NAME1:$IMAGE_TAG1
          
      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME1:$IMAGE_TAG1 
                # ✅ AKS CONTEXT SET
      - name: Deploy to AKS
        run: |
          # We use 'command invoke' because your runner is having trouble 
          # resolving the AKS DNS (lookup devtodoaks-... no such host)
          az aks command invoke \
            --resource-group psddg \
            --name devtodoakswestus \
            --command "kubectl apply -f deployment.yaml && kubectl apply -f service.yaml" \
            --file deployment.yaml \
            --file service.yaml
            
        
          
          
